const productData = [
    {
      id: 1,
      name: 'Shorts',
      brand: 'ActiveLife Gear',
      price: 29.99,
      image: '/images/shop/product/shop1.jpg',
      additionalImages: ['/images/shop/product/add1.jpg', '/images/shop/product/add2.jpg'],
    },
    {
      id: 2,
      name: 'T-Shirt',
      brand: 'Beach Paradise',
      price: 19.99,
      image: '/images/shop/product/shop2.jpg',
      additionalImages: ['/images/shop/product/add1.jpg', '/images/shop/product/add2.jpg'],
    },
    {
      id: 3,
      name: 'Jacket',
      brand: 'Black Tie Affairs',
      price: 59.99,
      image: '/images/shop/product/shop3.jpg',
      additionalImages: ['/images/shop/product/add1.jpg', '/images/shop/product/add2.jpg'],
    },
    {
      id: 4,
      name: 'Sunglasses',
      brand: 'Bohemian Bliss',
      price: 24.99,
      image: '/images/shop/product/shop4.jpg',
      additionalImages: ['/images/shop/product/add1.jpg', '/images/shop/product/add2.jpg'],
    },
    {
      id: 5,
      name: 'Hat',
      brand: 'Boho Chic Boutique',
      price: 14.99,
      image: '/images/shop/product/shop5.jpg',
      additionalImages: ['/images/shop/product/add1.jpg', '/images/shop/product/add2.jpg'],
    },
    {
      id: 6,
      name: 'Scarf',
      brand: 'Cashmere Cozy',
      price: 34.99,
      image: '/images/shop/product/shop6.jpg',
      additionalImages: ['/images/shop/product/add1.jpg', '/images/shop/product/add2.jpg'],
    },
    {
      id: 7,
      name: 'Jeans',
      brand: 'Chic Couture',
      price: 49.99,
      image: '/images/shop/product/shop7.jpg',
      additionalImages: ['/images/shop/product/add1.jpg', '/images/shop/product/add2.jpg'],
    },
    {
      id: 8,
      name: 'Dress',
      brand: 'Coastal Trends',
      price: 79.99,
      image: '/images/shop/product/shop8.jpg',
      additionalImages: ['/images/shop/product/add1.jpg', '/images/shop/product/add2.jpg'],
    },
    {
      id: 9,
      name: 'Boots',
      brand: 'Cozy Knits Co',
      price: 89.99,
      image: '/images/shop/product/shop9.jpg',
      additionalImages: ['/images/shop/product/add1.jpg', '/images/shop/product/add2.jpg'],
    },
    {
      id: 10,
      name: 'Blouse',
      brand: 'Dapper Styles',
      price: 39.99,
      image: '/images/shop/product/shop10.jpg',
      additionalImages: ['/images/shop/product/add1.jpg', '/images/shop/product/add2.jpg'],
    },
    {
      id: 11,
      name: 'Coat',
      brand: 'Denim Delight',
      price: 99.99,
      image: '/images/shop/product/shop11.jpg',
      additionalImages: ['/images/shop/product/add1.jpg', '/images/shop/product/add2.jpg'],
    },
    {
      id: 12,
      name: 'Suit',
      brand: 'Modern Man',
      price: 129.99,
      image: '/images/shop/product/shop12.jpg',
      additionalImages: ['/images/shop/product/add1.jpg', '/images/shop/product/add2.jpg'],
    },
    {
      id: 13,
      name: 'Cardigan',
      brand: 'Coastal Comfort',
      price: 44.99,
      image: '/images/shop/product/shop13.jpg',
      additionalImages: ['/images/shop/product/add1.jpg', '/images/shop/product/add2.jpg'],
    },
    {
      id: 14,
      name: 'Belt',
      brand: 'Urban Elegance',
      price: 22.99,
      image: '/images/shop/product/shop14.jpg',
      additionalImages: ['/images/shop/product/add1.jpg', '/images/shop/product/add2.jpg'],
    }
  ];
  
  export default productData;
  