const productData = [
  {
    id: 1,
  name: "Shorts",
  brand: "ActiveLife Gear",
  price: 29.99,
  image: "/images/shop/product/shop1.jpg",
  additionalImages: ["/images/shop/product/add1.jpg", "/images/shop/product/add2.jpg"],
  description: "The ActiveLife Gear Shorts are the perfect blend of comfort, style, and versatility. Designed for everyday wear, these shorts offer a relaxed fit with a breathable fabric that keeps you cool throughout the day. Whether you're heading to the gym, going for a casual outing, or simply lounging at home, these shorts provide the flexibility and ease you need. Crafted from high-quality, lightweight material, they ensure durability while maintaining a soft feel against the skin. The elastic waistband with an adjustable drawstring guarantees a snug yet customizable fit, making them ideal for various activities. Available in four sizes (S, M, L, XL), these shorts cater to all body types. Additionally, you can choose from three stylish colors—Red, Blue, and Black—allowing you to mix and match with your favorite outfits. The ActiveLife Gear Shorts are not just about comfort; they are also designed to keep you looking effortlessly stylish. The clean-cut design pairs well with t-shirts, tank tops, or even casual button-downs, making them a staple piece in your wardrobe. For those who appreciate both function and fashion, these shorts are a must-have. Upgrade your everyday style with the perfect balance of performance and comfort!",
  sizes: ["S", "M", "L", "XL"],
  colors: ["Red", "Blue", "Black"],
  },
  {
    id: 2,
    name: "T-Shirt",
    brand: "Beach Paradise",
    price: 19.99,
    image: "/images/shop/product/shop2.jpg",
    additionalImages: ["/images/shop/product/add1.jpg", "/images/shop/product/add2.jpg"],
    description: "Soft cotton T-shirt, perfect for casual outings.",
    sizes: ["M", "L", "XL"],
    colors: ["White", "Gray", "Black"],
  },
  {
    id: 3,
    name: "Jacket",
    brand: "Black Tie Affairs",
    price: 59.99,
    image: "/images/shop/product/shop3.jpg",
    additionalImages: ["/images/shop/product/add1.jpg", "/images/shop/product/add2.jpg"],
    description: "Warm and stylish jacket for winter.",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Black", "Brown"],
  },
  {
    id: 4,
    name: "Sunglasses",
    brand: "Bohemian Bliss",
    price: 24.99,
    image: "/images/shop/product/shop4.jpg",
    additionalImages: ["/images/shop/product/add1.jpg", "/images/shop/product/add2.jpg"],
    description: "Trendy sunglasses to enhance your style.",
    sizes: ["One Size"],
    colors: ["Black", "Brown", "Blue"],
  },
  {
    id: 5,
    name: "Hat",
    brand: "Boho Chic Boutique",
    price: 14.99,
    image: "/images/shop/product/shop5.jpg",
    additionalImages: ["/images/shop/product/add1.jpg", "/images/shop/product/add2.jpg"],
    description: "Stylish and lightweight summer hat.",
    sizes: ["S", "M", "L"],
    colors: ["Beige", "White", "Black"],
  },
  {
    id: 6,
    name: "Scarf",
    brand: "Cashmere Cozy",
    price: 34.99,
    image: "/images/shop/product/shop6.jpg",
    additionalImages: ["/images/shop/product/add1.jpg", "/images/shop/product/add2.jpg"],
    description: "Soft and warm cashmere scarf.",
    sizes: ["One Size"],
    colors: ["Red", "Blue", "Gray"],
  },
  {
    id: 7,
    name: "Jeans",
    brand: "Chic Couture",
    price: 49.99,
    image: "/images/shop/product/shop7.jpg",
    additionalImages: ["/images/shop/product/add1.jpg", "/images/shop/product/add2.jpg"],
    description: "Premium quality stretchable jeans.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blue", "Black"],
  },
  {
    id: 8,
    name: "Dress",
    brand: "Coastal Trends",
    price: 79.99,
    image: "/images/shop/product/shop8.jpg",
    additionalImages: ["/images/shop/product/add1.jpg", "/images/shop/product/add2.jpg"],
    description: "Elegant and flowy beach dress.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Pink", "Blue"],
  },
  {
    id: 9,
    name: "Boots",
    brand: "Cozy Knits Co",
    price: 89.99,
    image: "/images/shop/product/shop9.jpg",
    additionalImages: ["/images/shop/product/add1.jpg", "/images/shop/product/add2.jpg"],
    description: "Durable leather boots for all seasons.",
    sizes: ["7", "8", "9", "10", "11"],
    colors: ["Black", "Brown"],
  },
  {
    id: 10,
    name: "Blouse",
    brand: "Dapper Styles",
    price: 39.99,
    image: "/images/shop/product/shop10.jpg",
    additionalImages: ["/images/shop/product/add1.jpg", "/images/shop/product/add2.jpg"],
    description: "Chic and comfortable women’s blouse.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Blue", "Black"],
  },
  {
    id: 11,
    name: "Coat",
    brand: "Denim Delight",
    price: 99.99,
    image: "/images/shop/product/shop11.jpg",
    additionalImages: ["/images/shop/product/add1.jpg", "/images/shop/product/add2.jpg"],
    description: "Warm winter coat with a stylish design.",
    sizes: ["M", "L", "XL"],
    colors: ["Gray", "Black", "Navy"],
  },
  {
    id: 12,
    name: "Suit",
    brand: "Modern Man",
    price: 129.99,
    image: "/images/shop/product/shop12.jpg",
    additionalImages: ["/images/shop/product/add1.jpg", "/images/shop/product/add2.jpg"],
    description: "Formal suit perfect for business and weddings.",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Black", "Gray", "Blue"],
  },
  {
    id: 13,
    name: "bootire",
    brand: "Modern Man",
    price: 129.99,
    image: "/images/shop/product/shop13.jpg",
    additionalImages: ["/images/shop/product/add1.jpg", "/images/shop/product/add2.jpg"],
    description: "Formal suit perfect for business and weddings.",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Black", "Gray", "Blue"],
  }
];

export default productData;